# Generated by Django 4.1.7 on 2023-04-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='signuser',
            name='lastname',
        ),
    ]
